### ISSUE TITLE
imageview为自定义，项目中并没有采用装饰模式，实际使用时，建议采用装饰模式对控件进行扩展

### ISSUE THREAD

**Issue by luoqiang108** [DarksKnight/moveImageview#1]
imageview为自定义，项目中并没有采用装饰模式，实际使用时，建议采用装饰模式对控件进行扩展这个点能描述的在详细一点吗，我想进行扩展但是却感觉不知道具体怎么扩展

**Comment by DarksKnight** [comment]
这项目已经很久没弄了。。表示最近也没时间弄，不过可以看看DraggerViewHalper实现

**Comment by DarksKnight** [comment]
> imageview为自定义，项目中并没有采用装饰模式，实际使用时，建议采用装饰模式对控件进行扩展这个点能描述的在详细一点吗，我想进行扩展但是却感觉不知道具体怎么扩展

这项目已经很久没弄了。。表示最近也没时间弄，不过可以看看DraggerViewHalper实现

**Comment by luoqiang108** [comment]
好的，谢谢了




------------------ 原始邮件 ------------------
发件人: "DarksKnight"<notifications@github.com>; 
发送时间: 2019年4月22日(星期一) 下午3:43
收件人: "DarksKnight/moveImageview"<moveImageview@noreply.github.com>; 
抄送: "罗强"<2360299583@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [DarksKnight/moveImageview] imageview为自定义，项目中并没有采用装饰模式，实际使用时，建议采用装饰模式对控件进行扩展 (#1)



 
imageview为自定义，项目中并没有采用装饰模式，实际使用时，建议采用装饰模式对控件进行扩展这个点能描述的在详细一点吗，我想进行扩展但是却感觉不知道具体怎么扩展
  
这项目已经很久没弄了。。表示最近也没时间弄，不过可以看看DraggerViewHalper实现
